// Export Formats Generator: Markdown PRD, Linear/GitHub Batch, Executive Email, Mermaid.js

export function generatePRDMarkdown(items, sessionStats, userEmail) {
  const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const wpm = sessionStats?.wpm || 160;
  const timeSaved = sessionStats?.timeSaved || '18 minutes';
  const authorTag = userEmail ? `Author (Wispr Flow Verified): ${userEmail}` : 'Wispr Flow Voice Dictation';

  const actions = items.filter(i => i.category === 'action');
  const architecture = items.filter(i => i.category === 'architecture');
  const bugs = items.filter(i => i.category === 'bug');
  const insights = items.filter(i => i.category === 'insight');

  return `# 🚀 Product Specification & Architecture Document
*Generated by VoxFlow Studio (Voice-Driven Development with Wispr Flow)*
*${authorTag} | Date: ${dateStr} | Dictation Velocity: ${wpm} WPM | Time Saved: ~${timeSaved}*

---

## 1. Executive Summary & Vision
This document captures real-time architectural decisions, tactical deliverables, and vulnerability assessments synthesized directly from voice brainstorms and system design sessions using Wispr Flow.

- **Total Ideas Synthesized:** ${items.length} nodes
- **Critical Action Items:** ${actions.length} tasks
- **Architecture Blueprints:** ${architecture.length} specifications
- **Bugs/Defects Tracked:** ${bugs.length} items

---

## 2. System Architecture & Decisions
${architecture.length === 0 ? '_No architecture decisions recorded yet._' : architecture.map((a, idx) => `
### 2.${idx + 1} ${a.title}
- **Priority:** \`${a.priority}\`
- **Component Tags:** ${a.tags.map(t => `\`#${t}\``).join(' ')}
- **Specification:** ${a.detail || a.raw}
- **Recorded At:** ${a.createdAt}
`).join('\n')}

---

## 3. High-Priority Action Items & Deliverables
${actions.length === 0 ? '_No action items recorded yet._' : actions.map(act => `
- [ ] **[${act.priority}]** **${act.title}**
  - **Details:** ${act.detail || act.raw}
  - **Status:** \`${act.status.toUpperCase()}\`
  - **Labels:** ${act.tags.map(t => `\`#${t}\``).join(', ')}
`).join('\n')}

---

## 4. Defect & Resilience Backlog
${bugs.length === 0 ? '_No defects reported._' : bugs.map(b => `
- ⚠️ **[${b.priority}] ${b.title}**
  - **Impact:** ${b.detail || b.raw}
  - **Context:** Tagged under ${b.tags.join(', ')}
`).join('\n')}

---

## 5. Strategic Insights & Research Findings
${insights.length === 0 ? '_No insights recorded._' : insights.map(ins => `
- 💡 **${ins.title}** — ${ins.detail || ins.raw}
`).join('\n')}

---

*Verified Voice Build via [Wispr Flow](https://ref.wisprflow.ai/hhg).*
`;
}

export function generateLinearIssues(items, userEmail) {
  const actionsAndBugs = items.filter(i => i.category === 'action' || i.category === 'bug');
  if (actionsAndBugs.length === 0) {
    return '<!-- No actions or bugs currently captured to export -->';
  }

  const header = userEmail ? `<!-- Created with Wispr Flow Voice by ${userEmail} -->\n\n` : '';

  return header + actionsAndBugs.map((item, idx) => {
    const isBug = item.category === 'bug';
    return `### [Issue #${idx + 1}] ${isBug ? '🐛 BUG: ' : '🎯 TASK: '}${item.title}
**Priority:** ${item.priority} | **Type:** ${isBug ? 'Defect' : 'Feature Task'} | **Labels:** ${item.tags.join(', ')}

#### Description
${item.detail || item.raw}

#### Acceptance Criteria
- [ ] Implement and verify core functionality for "${item.title}"
- [ ] Add unit and end-to-end integration tests
- [ ] Verify zero regressions in affected modules (${item.tags.join(', ')})
- [ ] Code review and documentation updated

---
`;
  }).join('\n');
}

export function generateExecutiveEmail(items, sessionStats, userEmail) {
  const actions = items.filter(i => i.category === 'action');
  const architecture = items.filter(i => i.category === 'architecture');
  const bugs = items.filter(i => i.category === 'bug');

  return `Subject: Executive Sync Summary & Next Steps [Wispr Voice Brief]

Team,

Here is the quick executive summary from our voice architecture and strategy session:

Key Architectural Decisions:
${architecture.slice(0, 3).map(a => `• ${a.title}`).join('\n') || '• Alignment on current system design'}

Critical Immediate Actions:
${actions.slice(0, 4).map(a => `• [${a.priority}] ${a.title}`).join('\n') || '• No open blockers'}

Known Blockers / Vulnerabilities:
${bugs.slice(0, 3).map(b => `• ⚠️ ${b.title}`).join('\n') || '• None currently blocking'}

Productivity Note:
This briefing was dictated and synthesized using Wispr Flow (${userEmail || 'registered user'}) at ${sessionStats?.wpm || 160} words/minute, cutting documentation latency by 75%.

Best,
Engineering & Product Team`;
}

export function generateMermaidDiagram(items) {
  if (items.length === 0) {
    return `graph TD
  Start[Start Voice Dictation] --> Listen[VoxFlow Engine]
  Listen --> Items[Structured Nodes]`;
  }

  let code = `graph TD\n  %% Voice-Generated Cognitive Map\n`;
  code += `  classDef arch fill:#1e3a8a,stroke:#3b82f6,stroke-width:2px,color:#fff;\n`;
  code += `  classDef action fill:#065f46,stroke:#10b981,stroke-width:2px,color:#fff;\n`;
  code += `  classDef bug fill:#991b1b,stroke:#ef4444,stroke-width:2px,color:#fff;\n`;
  code += `  classDef insight fill:#854d0e,stroke:#eab308,stroke-width:2px,color:#fff;\n\n`;

  code += `  Hub["🎙️ Wispr Voice Core"]:::arch\n`;

  items.slice(0, 12).forEach((item, idx) => {
    const id = `Node${idx}`;
    const cleanLabel = (item.title || 'Item').replace(/["\n\r]/g, '').slice(0, 32);
    code += `  ${id}["${cleanLabel}"]:::${item.category}\n`;
    code += `  Hub --> ${id}\n`;
  });

  return code;
}
